apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  # grafana password
  GF_SECURITY_ADMIN_PASSWORD: "grafana_password"
  # gmail app password
  GF_SMTP_PASSWORD: "gmail_app_password"