apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      scrape_timeout:      10s
    
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    
    rule_files:

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'jenkins'
        metrics_path: /prometheus/
        static_configs:
        - targets: ['http://piplineapp.live']
