apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipeline-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - "piplineapp.live"
        - "grafana.piplineapp.live"
        - "prometheus.piplineapp.live"
      secretName: nginx-tls
  rules:
    - host: piplineapp.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  name: http