apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-host-pvc
spec:
  volumeName: grafana-host-pv
  accessModes: 
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 2Gi