apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
          - containerPort: 3000
          env:
          - name: GF_DATASOURCES_DEFAULT_URL
            value: "http://prometheus:9090"
          - name: GF_DATASOURCES_DEFAULT_ACCESS
            value: proxy
          - name: GF_SMTP_ENABLED
            value: "true"
          - name: GF_SMTP_HOST
            value: "smtp.gmail.com:465"
          - name: GF_SMTP_FROM_ADDRESS
            value: "yahya.muhaned@gmail.com"
          - name: GF_SMTP_SKIP_VERIFY
            value: "true"
          - name: GF_SMTP_USER
            value: "yahya.muhaned@gmail.com"
          envFrom:
          - secretRef:
              name: grafana-secret
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: grafana-volume
      # this is for using busybox as a persistentVolumeClaim (busybox defined in grafana-statefull.yaml)
      initContainers:
      - name: grafana-data-permission-fix
        image: busybox
        command: ["/bin/chmod","-R","777", "/grafana-data"]
        volumeMounts:
        - name: grafana-volume
          mountPath: /grafana-data
      volumes:
        # persistent volume
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: csi-pvc-grafana-csi-0