apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: onlinecelebration
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinecelebration
  template:
    metadata:
      labels:
        app: onlinecelebration
    spec:
      containers:
        - name: nginx-container
          image: muhanedyahya/onlinecelebration-nginx:v2
          envFrom:
          - configMapRef:
              name: laravel-configmap
          - secretRef:
              name: laravel-secret
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred