apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinecelebration-nginx
  template:
    metadata:
      labels:
        app: onlinecelebration-nginx
    spec:
      containers:
        - name: onlinecelebration-nginx
          image: muhanedyahya/onlinecelebration-nginx:v2
          envFrom:
          - configMapRef:
              name: laravel-configmap
          - secretRef:
              name: laravel-secret
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-secret