apiVersion: apps/v1
kind: Deployment
metadata: 
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinecelebration-php
  template:
    metadata:
      labels:
        app: onlinecelebration-php
    spec:
      containers:
        - name: onlinecelebration-php
          image: muhanedyahya/onlinecelebration-php:v7
          envFrom:
          - configMapRef:
              name: laravel-configmap
          - secretRef:
              name: laravel-secret
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-volume
              mountPath: /var/www/html/public/images
      imagePullSecrets:
        - name: docker-secret
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc