apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: onlinecelebration-php
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlinecelebration-php
  template:
    metadata:
      labels:
        app: onlinecelebration-php
    spec:
      containers:
        - name: onlinecelebration-php
          image: muhanedyahya/onlinecelebration-php:v2
          envFrom:
          - configMapRef:
              name: laravel-configmap
          - secretRef:
              name: laravel-secret
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred