apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      scrape_timeout:      10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['${PROMETHEUS_ADDRESS}']
      - job_name: 'jenkins'
        metrics_path: /prometheus/
        static_configs:
        - targets: ['${JENKINS_ADDRESS}']
